# Assignment — Numpy

20 exercises covering everything from Session 1: creating arrays, indexing/slicing, array arithmetic, broadcasting, and linear algebra operations.

Write your code in the empty cell below each exercise, and run it to check your output before moving on. Remember to `import numpy as np` at the top.

### Exercise 1 — Creating an array and checking its properties
Create a 1D array from `[12, 45, 7, 23, 56]`. Print its `shape` and its `dtype`.

In [ ]:
import numpy as np

# write your code here
arr = np.array([2, 45, 7, 23, 56]) 
print(arr.shape) 
print(arr.dtype) 

(5,)
int64


### Exercise 2 — Array of zeros
Create a 4×4 array of zeros and print it.

In [2]:
# write your code here
import numpy as np 
arr = np.zeros((4, 4)) 
print(arr) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Exercise 3 — Range with a step
Create an array starting at 2, going up to (but not including) 20, with a step of 3, using `np.arange()`.

In [ ]:
# write your code here

arr = np.arange(2, 20, 3)

print(arr)

[ 2  5  8 11 14 17]


### Exercise 4 — Evenly spaced values
Create an array of 5 evenly spaced values between 10 and 50 using `np.linspace()`.

In [4]:
# write your code here
arr = np.linspace(10, 50, 5) 

print(arr)

[10. 20. 30. 40. 50.]


### Exercise 5 — Indexing and slicing a 1D array
Given `arr = np.array([5, 12, 8, 21, 3, 17])`, print the element at index 2, the second-to-last element, and a slice from index 1 to 3 (inclusive).

In [5]:
arr = np.array([5, 12, 8, 21, 3, 17])

# write your code here
print(arr[2])
print(arr[-2])
print(arr[1:4])

8
3
[12  8 21]


### Exercise 6 — Indexing and slicing a 2D array
Given `matrix = np.array([[4, 8, 1], [6, 2, 9], [3, 7, 5]])`, print the element at row 1, column 2, and print the top-left 2×2 sub-matrix.

In [7]:
matrix = np.array([[4, 8, 1], [6, 2, 9], [3, 7, 5]])

# write your code here

print(matrix[1, 2])
print(matrix[:2, :2])

9
[[4 8]
 [6 2]]


### Exercise 7 — Element-wise arithmetic
Given `a = np.array([3, 6, 9])` and `b = np.array([1, 2, 3])`, print `a + b`, `a - b`, and `a * b`.

In [8]:
a = np.array([3, 6, 9])
b = np.array([1, 2, 3])

# write your code here
print(a + b)
print(a - b)
print(a * b)

[ 4  8 12]
[2 4 6]
[ 3 12 27]


### Exercise 8 — Broadcasting a scalar
Given `matrix = np.array([[1,2],[3,4],[5,6]])`, add 100 to every element using broadcasting, and print the result.

In [9]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])

# write your code here
result = matrix + 100

print(result)

[[101 102]
 [103 104]
 [105 106]]


### Exercise 9 — Matrix multiplication
Given `a = np.array([[2,0],[1,3]])` and `b = np.array([[1,4],[2,1]])`, compute their matrix product using `np.dot()`.

In [10]:
a = np.array([[2, 0], [1, 3]])
b = np.array([[1, 4], [2, 1]])

# write your code here
result = np.dot(a, b)

print(result)

[[2 8]
 [7 7]]


### Exercise 10 — Basic statistics
Given `arr = np.array([23, 45, 12, 67, 34, 89, 5])`, print its mean, max, min, and sum.

In [11]:
arr = np.array([23, 45, 12, 67, 34, 89, 5])

# write your code here
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.sum())

39.285714285714285
89
5
275


### Exercise 11 — Diagonal matrix
Create a diagonal matrix with `4, 7, 2, 9` on the diagonal using `np.diag()`.

In [12]:
# write your code here
matrix = np.diag([4, 7, 2, 9])

print(matrix)

[[4 0 0 0]
 [0 7 0 0]
 [0 0 2 0]
 [0 0 0 9]]


### Exercise 12 — Identity matrix
Create a 5×5 identity matrix using `np.eye()`.

In [13]:
# write your code here
matrix = np.eye(5)

print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Exercise 13 — Transpose
Given `matrix = np.array([[3,1,4],[1,5,9],[2,6,5]])`, print its transpose.

In [14]:
matrix = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])

# write your code here
print(matrix.T)

[[3 1 2]
 [1 5 6]
 [4 9 5]]


### Exercise 14 — Trace
Given `matrix = np.array([[6,2,1],[4,8,3],[7,5,9]])`, print its trace.

In [15]:
matrix = np.array([[6, 2, 1], [4, 8, 3], [7, 5, 9]])

# write your code here
print(np.trace(matrix))

23


### Exercise 15 — Determinant
Given `matrix = np.array([[2,1],[1,3]])`, print its determinant.

In [16]:
matrix = np.array([[2, 1], [1, 3]])

# write your code here
print(np.linalg.det(matrix))

5.000000000000001


### Exercise 16 — Inverse
Given `matrix = np.array([[3,2],[1,4]])`, print its inverse.

In [17]:
matrix = np.array([[3, 2], [1, 4]])

# write your code here
print(np.linalg.inv(matrix))

[[ 0.4 -0.2]
 [-0.1  0.3]]


### Exercise 17 — Rank
Given `matrix = np.array([[1,2,3],[2,4,6],[1,1,1]])`, print its rank. (Hint: notice something about the first two rows before you run it — what do you expect the rank to be, and why?)

In [18]:
matrix = np.array([[1, 2, 3], [2, 4, 6], [1, 1, 1]])

# write your code here
print(np.linalg.matrix_rank(matrix))

2


### Exercise 18 — Boolean indexing
Given `arr = np.array([15, 8, 42, 3, 27, 19])`, use boolean indexing to print only the values greater than 15.

In [19]:
arr = np.array([15, 8, 42, 3, 27, 19])

# write your code here
print(arr[arr > 15])

[42 27 19]


### Exercise 19 — Reshape
Create an array of 12 numbers using `np.arange(12)`, then reshape it into a 3×4 matrix and print it.

In [20]:
# write your code here
arr = np.arange(12)

matrix = arr.reshape(3, 4)

print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Exercise 20 — Comprehensive: axis-based operations
Given `matrix = np.array([[10,20,30],[40,50,60]])`, print the sum along `axis=0`, the sum along `axis=1`, and the overall mean of the whole matrix (no axis argument).

In [21]:
matrix = np.array([[10, 20, 30], [40, 50, 60]])

# write your code here
matrix = np.array([[10, 20, 30],
                   [40, 50, 60]])

print(matrix.sum(axis=0))
print(matrix.sum(axis=1))
print(matrix.mean())

[50 70 90]
[ 60 150]
35.0


---
### Done! 🎉
Double check your outputs, then send this notebook back — you'll get the fully solved version afterward.